% SPM Configuration file
% automatically generated by the MATLABBATCH utility function GENCODE
%_______________________________________________________________________
% Copyright (C) 2008 Wellcome Trust Centre for Neuroimaging

% $Id: spm_cfg_mlb_preamble.m 1373 2008-04-11 14:24:03Z spm $

rev = '$Rev: 1373 $';
